## Importing Modules 

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

## Loading Dataset 

In [4]:
data = pd.read_csv('loan_approval_dataset.csv')
data.head(5) 

loan_id  no_of_dependents      education self_employed  income_annum  \
0        1                 2       Graduate            No       9600000   
1        2                 0   Not Graduate           Yes       4100000   
2        3                 3       Graduate            No       9100000   
3        4                 3       Graduate            No       8200000   
4        5                 5   Not Graduate           Yes       9800000   

   loan_amount  loan_term  cibil_score  residential_assets_value  \
0     29900000         12          778                   2400000   
1     12200000          8          417                   2700000   
2     29700000         20          506                   7100000   
3     30700000          8          467                  18200000   
4     24200000         20          382                  12400000   

   commercial_assets_value  luxury_assets_value  bank_asset_value loan_status  
0                 17600000             22700000           8000000    Approved  
1                  2200000              8800000           3300000    Rejected  
2                  4500000             33300000          12800000    Rejected  
3                  3300000             23300000           7900000    Rejected  
4                  8200000             29400000           5000000    Rejected

## EDA 

In [5]:
data.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   loan_id                   4269 non-null   int64 
 1   no_of_dependents          4269 non-null   int64 
 2   education                 4269 non-null   object
 3   self_employed             4269 non-null   object
 4   income_annum              4269 non-null   int64 
 5   loan_amount               4269 non-null   int64 
 6   loan_term                 4269 non-null   int64 
 7   cibil_score               4269 non-null   int64 
 8   residential_assets_value  4269 non-null   int64 
 9   commercial_assets_value   4269 non-null   int64 
 10  luxury_assets_value       4269 non-null   int64 
 11  bank_asset_value          4269 non-null   int64 
 12  loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB


In [6]:
data.describe() 

loan_id  no_of_dependents  income_annum   loan_amount    loan_term  \
count  4269.000000       4269.000000  4.269000e+03  4.269000e+03  4269.000000   
mean   2135.000000          2.498712  5.059124e+06  1.513345e+07    10.900445   
std    1232.498479          1.695910  2.806840e+06  9.043363e+06     5.709187   
min       1.000000          0.000000  2.000000e+05  3.000000e+05     2.000000   
25%    1068.000000          1.000000  2.700000e+06  7.700000e+06     6.000000   
50%    2135.000000          3.000000  5.100000e+06  1.450000e+07    10.000000   
75%    3202.000000          4.000000  7.500000e+06  2.150000e+07    16.000000   
max    4269.000000          5.000000  9.900000e+06  3.950000e+07    20.000000   

       cibil_score  residential_assets_value  commercial_assets_value  \
count  4269.000000              4.269000e+03             4.269000e+03   
mean    599.936051              7.472617e+06             4.973155e+06   
std     172.430401              6.503637e+06             4.388966e+06   
min     300.000000             -1.000000e+05             0.000000e+00   
25%     453.000000              2.200000e+06             1.300000e+06   
50%     600.000000              5.600000e+06             3.700000e+06   
75%     748.000000              1.130000e+07             7.600000e+06   
max     900.000000              2.910000e+07             1.940000e+07   

       luxury_assets_value  bank_asset_value  
count         4.269000e+03      4.269000e+03  
mean          1.512631e+07      4.976692e+06  
std           9.103754e+06      3.250185e+06  
min           3.000000e+05      0.000000e+00  
25%           7.500000e+06      2.300000e+06  
50%           1.460000e+07      4.600000e+06  
75%           2.170000e+07      7.100000e+06  
max           3.920000e+07      1.470000e+07

In [7]:
data.isnull().sum() 

loan_id                     0
no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

## Replacing String Values using Label Encoding 

The List of Columns having string values are - 

1. education 

2. self_employed

3. loan_status 

In [8]:
data['education'].unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [9]:
data['self_employed'].unique()

array([' No', ' Yes'], dtype=object)

In [10]:
data['loan_status'].unique()

array([' Approved', ' Rejected'], dtype=object)

In [11]:
data['education'] = data['education'].replace([' Graduate', ' Not Graduate'], [1, 0])
data['self_employed'] = data['self_employed'].replace([' Yes', ' No'], [1, 0])
data['loan_status'] = data['loan_status'].replace([' Approved', ' Rejected'], [1, 0]) 

C:\Users\admin\AppData\Local\Temp\ipykernel_12512\1982064399.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['education'] = data['education'].replace([' Graduate', ' Not Graduate'], [1, 0])
C:\Users\admin\AppData\Local\Temp\ipykernel_12512\1982064399.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['self_employed'] = data['self_employed'].replace([' Yes', ' No'], [1, 0])
C:\Users\admin\AppData\Local\Temp\ipykernel_12512\1982064399.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be rem

In [12]:
data['education'].unique()

array([1, 0])

In [13]:
data['self_employed'].unique()

array([0, 1])

In [14]:
data['loan_status'].unique()

array([1, 0])

## Building the Model 

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report 

In [19]:
model = DecisionTreeClassifier()

In [20]:
X = data.drop(['loan_id', 'loan_status'], axis = 1)
y = data['loan_status'] 

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.3) 

In [22]:
model.fit(X_train, y_train) 

DecisionTreeClassifier()

In [23]:
prediction = model.predict(X_test) 

In [24]:
accuracy_score(y_test, prediction) * 100 

97.65807962529274

In [25]:
print(classification_report(y_test, prediction)) 

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       471
           1       0.98      0.99      0.98       810

    accuracy                           0.98      1281
   macro avg       0.98      0.97      0.97      1281
weighted avg       0.98      0.98      0.98      1281



## Checking Accuracy for Multiple Models 

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier 

In [27]:
models = {'DecisionTreeClassifier': DecisionTreeClassifier(),
         'LogisticRegression': LogisticRegression(),
         'RandomForestClassifier': RandomForestClassifier(),
         'XGBClassifier': XGBClassifier()}

for model_name, mod in models.items():
    print(f"\nChecking for {model_name}")
    model = mod
    
    model.fit(X_train, y_train)
    
    prediction = model.predict(X_test) 
    
    print(f"Accuracy Score - {accuracy_score(y_test, prediction) * 100 }\n")
    print(classification_report(y_test, prediction)) 


Checking for DecisionTreeClassifier
Accuracy Score - 97.81420765027322

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       471
           1       0.98      0.99      0.98       810

    accuracy                           0.98      1281
   macro avg       0.98      0.97      0.98      1281
weighted avg       0.98      0.98      0.98      1281


Checking for LogisticRegression
Accuracy Score - 72.6775956284153

              precision    recall  f1-score   support

           0       0.77      0.37      0.50       471
           1       0.72      0.93      0.81       810

    accuracy                           0.73      1281
   macro avg       0.74      0.65      0.66      1281
weighted avg       0.74      0.73      0.70      1281


Checking for RandomForestClassifier


c:\Users\admin\Downloads\AAD Project\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy Score - 97.81420765027322

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       471
           1       0.98      0.99      0.98       810

    accuracy                           0.98      1281
   macro avg       0.98      0.97      0.98      1281
weighted avg       0.98      0.98      0.98      1281


Checking for XGBClassifier
Accuracy Score - 97.50195160031225

              precision    recall  f1-score   support

           0       0.97      0.96      0.97       471
           1       0.98      0.98      0.98       810

    accuracy                           0.98      1281
   macro avg       0.97      0.97      0.97      1281
weighted avg       0.97      0.98      0.97      1281



## Saving Model 

Since DecisionTreeClassifier has given the best accuracy, we will use it for building the API 

In [28]:
model = DecisionTreeClassifier()

In [29]:
model.fit(X_train, y_train) 

DecisionTreeClassifier()

In [30]:
import pickle
import joblib

In [31]:
with open("final_model.pkl", "wb") as f:
    pickle.dump(model, f)
    
joblib.dump(model, "final_model.joblib") 

['final_model.joblib']

In [32]:
test_data = data = [[4, 1, 1, 10000000, 100000, 2, 800, 100000, 100000, 100000, 100000]]

In [33]:
model.predict(test_data) 

c:\Users\admin\Downloads\AAD Project\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [34]:
loaded_model = joblib.load("final_model.joblib") 

In [35]:
loaded_model.predict(test_data) 

c:\Users\admin\Downloads\AAD Project\.venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [1]:
import sklearn; print(sklearn.__version__) 

1.3.2


In [68]:
!pip install --upgrade scikit-learn 

   ---------------------------------------- 11.1/11.1 MB 11.4 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.1
    Uninstalling scikit-learn-1.5.1:
      Successfully uninstalled scikit-learn-1.5.1


  You can safely remove it manually.

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!pip uninstall scikit-learn 

^C
